# ========================
# SERVER
# ========================
server.port=9090

# ========================
# DATABASE (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ParqueaYa
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ========================
# SWAGGER / OPENAPI
# ========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=list

# ========================
# JWT
# ========================
jwt.secret=ParqueaYa2026SecretKeyMuySeguraDeAlMenos256BitsParaHS256Algorithm!!
jwt.expiration=86400000

# ========================
# GOOGLE OAUTH2
# ========================
google.clientId=262408051644-hnc75e6jmpkrtnbsdeakhvlmko9avpuc.apps.googleusercontent.com

